name: RGUK Bot deploy

on:
  push:
    branches:
      - '**'

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Sync files woth host via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          rm: false
          overwrite: true
          source: ./*
          target: ${{ secrets.DESTINATION_FOLDER }}
